version: '2'
services:
  ngx:
    image: nginx
    restart: always
    ports:
      - "8786:80"
    depends_on:
      - bpm
      - axelor
    links:
      - bpm
      - axelor
    environment:
      - VER=3.2
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      #- ./webapps:/home/webapps

  bpm:
    build: ./bpm
    image: shawoo/bpm:pouchdb
    restart: always
    #ports:
    #  - "3303:3303"
    command: /bin/bash ./start.sh
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

      - ./bpm/bpm.js:/opt/bpm/bpm.js
      - ./bpm/OAuthApi.js:/opt/bpm/OAuthApi.js
      - ./bpm/oauth2/:/opt/bpm/oauth2/
      - ./bpm/start.sh:/opt/bpm/start.sh
    environment:
      - VER=202104150
      - TZ=Asia/Shanghai
      - LD_LIBRARY_PATH=/usr/local/sap/nwrfcsdk/lib
    depends_on:
      - redisdb
    links:
      - redisdb
      - axelor

  redisdb:
    image: redis
    restart: always
    #ports:
    #  - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  axelor:
    image: shawoo/axelor
    restart: always
    depends_on:
      - mysqldb
      - postgresdb
    links:
      - mysqldb
      - postgresdb
    #ports:
    #  - "8786:8080" 
    command: start #/bin/bash
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    stdin_open: true
    tty: true
    privileged: true

  postgresdb:
    image: postgres:10
    #volumes:
    #  - "./postgresql/data:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor

  mysqldb:
    image: shawoo/mysql:5.7.15
    restart: always
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: axelor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mysql/data:/var/lib/mysql/
      - ./mysql/config:/etc/mysql/conf.d/

