version: '2'
services:
  axelor:
    image: shawoo/axelor
    restart: always
    depends_on:
      - mysqldb
      - postgresdb
    links:
      - mysqldb
      - postgresdb
    ports:
      - "8786:8080" 
    command: start #/bin/bash
    #volumes:
      #- ./ROOT:/usr/local/tomcat/webapps/ROOT
    stdin_open: true
    tty: true
    privileged: true

  postgresdb:
    image: postgres:10
    #volumes:
    #  - "./postgresql/data:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor

  mysqldb:
    image: shawoo/mysql:5.7.15
    restart: always
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: axelor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mysql/data:/var/lib/mysql/
      - ./mysql/config:/etc/mysql/conf.d/

