version: '2'
services:
  ngx:
    image: nginx
    restart: always
    ports:
      - "8786:80"
    depends_on:
      - bpm
      - axelor
    links:
      - bpm
      - axelor
    environment:
      - VER=3.1
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  bpm:
    build: ./bpm
    image: shawoo/bpm:pouchdb
    restart: always
    #ports:
    #  - "3303:3303"
    command: /bin/bash ./start.sh
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

      - ./bpm/bpm.js:/opt/bpm/bpm.js
      - ./bpm/OAuthApi.js:/opt/bpm/OAuthApi.js
      - ./bpm/oauth2/:/opt/bpm/oauth2/
      - ./bpm/start.sh:/opt/bpm/start.sh

      - ./share:/opt/bpm/public/share
    environment:
      - VER=202104150
      - TZ=Asia/Shanghai
      - LD_LIBRARY_PATH=/usr/local/sap/nwrfcsdk/lib
    depends_on:
      - redisdb
    links:
      - redisdb
      - axelor

  redisdb:
    image: redis
    restart: always
    #ports:
    #  - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  axelor:
    image: shawoo/axelor:5.4.6-6.1.3
    restart: always
    depends_on:
      - mysqldb
      - postgresdb
    links:
      - mysqldb
      - postgresdb
    #ports:
    #  - "8786:8080" 
    command: start #/bin/bash
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./ROOT-5.4.6-6.1.2.war:/usr/local/tomcat/webapps/ROOT.war
      - ./abc:/usr/local/tomcat/abc
      - ./entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./data:/app/data
      - ./modules/phx-mro:/app/axelor-erp/modules/axelor-open-suite/phx-mro
    working_dir: /app/axelor-erp/modules/axelor-open-suite/phx-mro
    #working_dir: /usr/local/tomcat/webapps/ROOT
    environment:
      modules: phx-mor-0.0.1
    stdin_open: true
    tty: true
    privileged: true

  postgresdb:
    image: postgres:10
    #volumes:
    #  - "./postgresql/data:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    links:
      - postgresdb
    ports:
      - "5433:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=wuzhiping@qq.com
      - PGADMIN_DEFAULT_PASSWORD=100861

  mysqldb:
    image: shawoo/mysql:5.7.15
    restart: always
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: axelor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mysql/data:/var/lib/mysql/
      - ./mysql/config:/etc/mysql/conf.d/

